# Generated by Django 3.0.3 on 2020-03-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortKeyword',
        ),
    ]
