# Generated by Django 3.0.3 on 2020-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200228_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='product.ProductCategory', to='product.Category'),
        ),
    ]
