# Generated by Django 3.0.3 on 2020-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200227_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tagline',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
