# Generated by Django 3.0.3 on 2020-02-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_section_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgage_url',
            new_name='image_url',
        ),
    ]
