# Generated by Django 3.0.3 on 2020-02-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200227_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sort_keywords',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_real_category',
            field=models.BooleanField(null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'products_categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='product.ProductCategory', to='product.Category'),
        ),
    ]
