# Generated by Django 3.0.3 on 2020-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200228_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='Product',
            new_name='product',
        ),
    ]
