# Generated by Django 3.0.3 on 2020-03-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('detailed_address', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('agreement', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('count', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'asks',
            },
        ),
    ]
