# Generated by Django 3.0.3 on 2020-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200225_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('count', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
    ]
