# Generated by Django 3.0.3 on 2020-03-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ask',
            table='asks',
        ),
    ]
